const { withAppBuildGradle } = require('expo/config-plugins');

// Google ML Kit is opt-in: the Anyline SDK declares it compileOnly and does not export it, so a
// host app that uses face detection or native barcode detection has to add the module itself.
//
// expo-build-properties cannot add arbitrary Gradle dependencies, and android/ is generated by
// `expo prebuild` and gitignored, so the dependency has to be injected here to survive a clean
// checkout. A bare / ejected app can instead paste the line straight into android/app/build.gradle.
//
// NOT REGISTERED BY DEFAULT. None of the example scan view configs set faceDetectionEnabled, so
// this app does not need ML Kit. The plugin is kept as the worked reference for integrators who
// do. To enable face detection on Universal ID / MRZ, add this line back to the "plugins" array in
// app.json, after "./plugins/withCustomAppBuildGradle.js":
//
//     "./plugins/withMlKitDependency.js",
//
// It is left out of app.json rather than commented there because .devops/prepare_release.sh runs
// jq over app.json, and jq rejects comments.
const ML_KIT_DEPENDENCY = "    implementation 'com.google.mlkit:face-detection:16.1.7'";

module.exports = function withMlKitDependency(config) {
  return withAppBuildGradle(config, (config) => {
    const contents = config.modResults.contents;

    if (contents.includes('com.google.mlkit:face-detection')) {
      return config;
    }

    const dependenciesPattern = '\ndependencies {\n';
    const dependenciesIndex = contents.indexOf(dependenciesPattern);

    if (dependenciesIndex === -1) {
      throw new Error(
        "withMlKitDependency: no 'dependencies {' block found in android/app/build.gradle."
      );
    }

    const pivot = dependenciesIndex + dependenciesPattern.length;
    config.modResults.contents =
      contents.slice(0, pivot) + ML_KIT_DEPENDENCY + '\n' + contents.slice(pivot);

    return config;
  });
};