project 'RNExampleApp.xcodeproj'
platform :ios, '10.0'

target 'RNExampleApp' do
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'DevSupport',
    'RCTNetwork',
  ]
  pod 'AnylineReact', path: '../node_modules/anyline-ocr-react-native-module/ios'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/Yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|

    # The following is needed to ensure the "archive" step works in XCode.
    # It removes React & Yoga from the Pods project, as it is already included in the main project.
    # Without this, you'd see errors when you archive like:
    # "Multiple commands produce ... libReact.a"
    # "Multiple commands produce ... libyoga.a"

    targets_to_ignore = %w(yoga React)
    
    if targets_to_ignore.include? target.name
      target.remove_from_project
    end

  end
end