project 'RNExampleApp.xcodeproj'
platform :ios, '9.0'

target 'RNExampleApp' do
  pod 'React', :path => '../node_modules/react-native'
  pod 'AnylineReact', path: '../node_modules/anyline-ocr-react-native-module/ios'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/Yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
end