project 'RNExampleApp.xcodeproj'
platform :ios, '8.0'

target 'RNExampleApp' do
  pod 'React', :path => '../node_modules/react-native'
  pod 'AnylineReact', path: '../node_modules/anyline-ocr-react-native-module/ios'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/Yoga'
end